Update irctc.yml

diff --git a/.github/workflows/irctc.yml b/.github/workflows/irctc.yml
--- a/.github/workflows/irctc.yml
+++ b/.github/workflows/irctc.yml
@@ -31,7 +31,12 @@ jobs:
     - run: |
         sudo timedatectl set-timezone Asia/Kolkata
         pip install -r irctc-captcha-solver/requirements.txt
-        python3 irctc-captcha-solver/app.py "" # python3 irctc-captcha-solver/app.py "" is used for models to load before starting tatkal tickets 
+        if [ -f "irctc-captcha-solver/app.py" ]; then
+          python3 irctc-captcha-solver/app.py "" # python3 irctc-captcha-solver/app.py "" is used for models to load before starting tatkal tickets 
+        else
+          echo "Error: irctc-captcha-solver/app.py not found."
+          exit 1
+        fi
         PASSWORD=$(jq -r '.inputs.PASSWORD' $GITHUB_EVENT_PATH)
         USERNAME=$(jq -r '.inputs.USERNAME' $GITHUB_EVENT_PATH)
         UPI_ID=$(jq -r '.inputs.UPI_ID' $GITHUB_EVENT_PATH)
@@ -43,9 +48,6 @@ jobs:
         echo PASSWORD=$PASSWORD >> $GITHUB_ENV
         echo USERNAME=$USERNAME >> $GITHUB_ENV
         echo UPI_ID=$UPI_ID >> $GITHUB_ENV
-
-
-    # python3 irctc-captcha-solver/app.py "" is used for models to load before starting tatkal tickets 
 
     - name: Install Node.js and npm
       uses: actions/setup-node@v4
